Fixed pull #83 and made enlisting matter again
aristotlepenguin/endless-war pull request #86
Opened 2021-05-08 11:47 UTC by DaKATFailsImmenselyAtCoding

Enlisting/vouching changes have been done to make enlistments more permanent n have been agreed on by a big part of the community:
-Enlisting can only be done in gang bases.
-Voucher and vouched have to be in the same zone when one wants to vouch the other.
-Renouncing now gives flavour text, if someone wants to stop being a gang member they better suicide or die in pvp helping their respective gang. Enlisting is a one way road.

Now I'll copy the things I had in the older pull and fixed to match Magicks' reorganizing:
-With !unpossessfishingrod, !unpossessrod and !unpossess ghosts should be able to unpossess a fleshbag's rod without having to miss a reel or uninhabit.
-Created !github, !pulls and !tutorial (links to "Category:Gameplay" in the wiki) as external link commands.
-Created alts for all Casino games removing "slime". As an example, to play "slimeroulette" now you can simply do "!roulette".
-!parkour is an alt for !jump and there is a small chance of succeeding at jumping.

I'm pretty sure this code is fine, but I'd still appreciate some more experienced coder checking it. Thanks! :)

2021-05-08 11:56 UTC, farafrog44 reviewed
cringus

2021-05-08 16:34 UTC, magicksRampage requested changes
please test your code before submitting a pull request

2021-05-08 16:34 UTC, magicksRampage commented on client.py
> +	ewcfg.cmd_tutorial: ewcmd.tutorial
missing commas

2021-05-08 16:34 UTC, magicksRampage commented on ew/faction.py
> +	if vouchee_data,poi != user_data.poi:
vouchee_data.poi

2021-05-08 16:34 UTC, magicksRampage commented on ew/spooky.py
> +from .spooky import EwFish
this import makes no sense

2021-05-08 19:17 UTC, DaKATFailsImmenselyAtCoding commented
Sorry bout those mistakes and removing mechanics without thinkin about it lol, my bad

2021-05-17 11:50 UTC, DaKATFailsImmenselyAtCoding commented
Outdated, will do a new pull

2021-05-17 11:50 UTC, closed without merging